### PR TITLE
docs: A step-by-step CI/CD guide

### PR DESCRIPTION
**Pull request by davidvc**

### CODE REVIEW

**Comment by bethesque** [comment]
Hi David. Man I love this! The diagrams are great, and the content is so well thought out. Thank you!

Writing a document that describes how to go from "0 pact" to "you have the most possible pact set up" is exactly what the guide at https://docs.pact.io/pact_nirvana was supposed to do. That guide is sorely out of date now however, and I've been itching to update it, but haven't had the time. My worry by adding these new docs is that we've now duplicated a lot of content, rather than improving and sharpening what we have. We've reached the stage where there's too many docs, rather than not enough, and they need to be better organised.

David, would you be interested in taking the content you have and working out what in the existing guide can be replaced by your content, and if there's anything in the existing content that might be valuable to add? I'd love to see the two merged together, rather than existing as separate resources.

**Comment by davidvc** [comment]
I agree that we want to merge the two. I hesitate to commit to taking that on, but I recognize there's no point in posting something and then having it sit there.  Got to finish what I started :)

Would you have time to take a first pass at a merge based on what you're looking for, and then I can come in and offer edits and we can collaborate in that way?  Even just laying out a *structure* of what you think you want to express, and I can drop in the details from this page? Trying to find a way where we can get this done without a lot of back and forth.

**Comment by bethesque** [comment]
I'm unlikely to have time to pick this up over the next few weeks, but I don't want to lose momentum on it. This might be a good opportunity to get @YOU54F involved.

**Comment by YOU54F** [comment]
> Would you have time to take a first pass at a merge based on what you're looking for, and then I can come in and offer edits and we can collaborate in that way? Even just laying out a _structure_ of what you think you want to express, and I can drop in the details from this page?

Hey @davidvc , agreed that this is epic, diagrams especially!

I’m to aid in merging this into the main path to nirvana guide and you can offer edits. You’ve already done so much and community curated content is so valuable.

I will put it on my list of actions for this week and get you a copy over shortly. Thanks again!

I had seen your other PR as well so will review both 🙌

**Comment by davidvc** [comment]
Great, thanks!!

**Comment by davidvc** [comment]
By the way, if you want to do more diagrams, or enhance the ones I have, head over to websequencediagrams.com

**Comment by YOU54F** [comment]
> By the way, if you want to do more diagrams, or enhance the ones I have, head over to websequencediagrams.com

Cheers buddy, I thought they looked familiar, I've used that tool before at my last client site with good results.

The content is excellent btw, just had a quick read through. Thanks for taking the time, I'm sure this has been really valuable for your team and it is really nice to see you take the time to share it back!

**Comment by YOU54F** [comment]
Hey @davidvc,

Just looking at the CI/CD setup guide, which is our path to Pact Nirvana, and taken your headings and kind of grouped them under the existing pages

They are as follows

1. Talk
2. Spike
3. Write and verify and real pact
4. Automate the contract and verification results exchange
5. Allow contracts to change without breaking your builds
6. Ensure backwards compatiblity between the latest provider and production consumer
7. Use the Pact 'Matrix' as a gateway to deployments
8. Prevent missing verifications

Yours are 

## Get prepared: learn about Pact
## Start your engines: get team alignment
## Silver level: manually integrate with Pact Broker
## Gold level - integrate with your PR pipelines
## Platinum level: Add can-i-deploy with branch tag to PR pipelines
## Diamond level - Add Pact to your deploy pipelines

I've tried to map these roughly to your heading contents, there is a nice amount of overlap. I love the idea of different badges associated with the different levels of achievement, adds a bit of gamification. The intro page, might be a nice to set to pre-amble about the different levels. Shouldn't be too much work to get this weaved in. 


1. Talk
## Get prepared: learn about Pact
## Start your engines: get team alignment

2. Spike
3. Write and verify and real pact
## Bronze level: get a single test working manually
### Write a consumer test with no provider state
### Manually run the provider verification test

4. Automate the contract and verification results exchange
## Silver level: manually integrate with Pact Broker
### Manually publish the pact to the Pact Broker
### Manually verify using the Pact Broker

## Gold level - integrate with your PR pipelines
### Publish the pact from your consumer PR pipeline
### Modify the consumer commit pipeline to tag with master branch
### Add a step at the beginning of the pipeline to apply the tag with the name of your main branch (e.g. master, trunk or main)
### Verify the pact in your provider PR validation pipeline

5. Allow contracts to change without breaking your builds
6. Ensure backwards compatiblity between the latest provider and production consumer

## Platinum level: Add can-i-deploy with branch tag to PR pipelines
### Add can-i-deploy to consumer PR pipeline
### Add a new provider verification job
### Add can-i-deploy webhook to Pact Broker

7. Use the Pact 'Matrix' as a gateway to deployments
8. Prevent missing verifications
## Diamond level - Add Pact to your deploy pipelines
### Add tagging to your commit pipelines
### Add can-i-deploy to your commit pipelines
### Add can-i-deploy to environments to your PR pipelines
### What if we use a release branch?
### Modify can-i-deploy in your consumer and provider PR validation pipelines


## Extra Credit - Add provider state


## Honors Course - Pending Pacts
## Honors Course - Verifying Pacts that are Works in Progress
## Honors Course - Working with Feature Flags

**Comment by davidvc** [comment]
Yes, this looks like a great approach.  Gamification for the win! :)

**Comment by davidvc** [comment]
For one of the honors courses: I'm going to put together a writeup on my understanding about how to approach feature toggles and other config-driven changes (where it's the same code but different versions of the contract due to configuration). Hope to have a draft PR for this in the next day or so. It probably needs to be its own page, it's a fairly rich topic

**Comment by bethesque** [comment]
Oh wow, I go to sleep and look what happens! ❤️ 

David, I'd love your thoughts about feature toggles on https://pact.canny.io/feature-requests/p/add-better-support-for-workflows-that-are-managed-by-feature-toggles-rather-than We're very aware that we need to improve our support for them.

You seem very familiar with all the docs, but just in case, wanted to make sure you've seen this - https://docs.pact.io/pact_broker/tags#using-tags-with-feature-toggles-instead-of-feature-branches I'd be keen to get your thoughts on that approach.

**Comment by davidvc** [comment]
Hi, @bethesque , yes I remember that feature toggles doc now.  I think Matt had pointed me to this earlier.

The way of identifying each feature toggle as a different version makes sense to me, and is aligned with my understanding that the same code version has multiple pacticipant versions, one for each active toggle.  Note this approach applies for any type of configuration that can change the behavior of the code (and in particular change the expectations of the contract).

The trick is how to make sure the provider verifies against all those versions. Your proposal was to use WIP for this, but I don't think it works. That's what led me to [this thread on the Slack channel. ](https://pact-foundation.slack.com/archives/C5F4KFKR8/p1644531903971329)

The definition of a WIP pact, from your docs:
```
A "work in progress" pact is a pact that:

    - is the latest for its branch (as specified by its tags)
    - does not have a successful verification result from the current provider branch (as specified by its tags) - that is, the pact is in "pending" state.
    - was not explicitly specified in the consumer version selectors
  ```

Which led me to this question

```
I was looking at using WIP to manage feature flag variations. But if WIP only runs for pending pacts, 
how do I make sure that a feature flag pact that previously passed verification will get verified 
in the future, when the provider changes?
```

And then after a few attempts at getting a response, Matt came back saying:

```
I’ve been thinking about this, and am not sure WIP pacts is the best approach.
```
And what followed was a long thread on the subject...

I don't know the answer, but the problem statement is: the provider needs to verify against not just the latest consumer version for a tag, but against *all* consumer versions for a tag that have the same git sha, where that git sha is the latest sha on the branch.

So for example when sha 05ac371 is deployed to staging, then versions 05ac371, 05ac371+featA and 05ac371+featB should all be tagged with `staging`.

Now if I want to know if the other side of the pact can deploy to staging, I need to make sure all three of those versions get verified.

The way I was thinking of it was that we use the --all, just like with releases.  You would have to make sure when you deploy a new git sha to staging, that the tag is removed for all versions with the old git sha. That's a lot of bookkeeping but I think it is doable.

Would love your thoughts.

**Comment by davidvc** [comment]
Sorry, I tried my best to explain what I was thinking but it still sounds overly complex. I believe there is a clear way to explain it, I just haven't gotten there yet.

Reminds me of some author who after submitting an essay wrote to his editor "sorry it's so long; I didn't have time to make it shorter."

**Comment by PauloGoncalvesBH** [comment]
hi @davidvc, this PR is being very constructive.

I wanted to make a suggestion, I saw that the '_diamond_' level diagrams are focused on the provider side and that the '_gold_' and '_platinum_' level diagrams are focused on the consumer side.
What do you think about inserting more images of each?

### Example:
Create '_diamond_' level diagram that PR starts from the consumer side and goes through all steps, including webhook.

**If you give me access to your repository and also to the original files I can make these diagrams and upload a new commit, then you see what you think.**

> I even made a diagram of the 'diamond' level in a repository of mine, but it's in PT-BR, if you want to see it: https://github.com/PauloGoncalvesBH/nirvana-teste-de-contrato#sobre-o-reposit%C3%B3rio

**Comment by davidvc** [comment]
Hi, @PauloGoncalvesBH . I like your diagrams! Rather than updating this PR, can you coordinate with @YOU54F ? He is taking this "raw material" and merging it into the existing guides.

**Comment by YOU54F** [comment]
Hey all,

Have taken a first pass at migrating all this great stuff into the pact nirvana guide,

https://github.com/pact-foundation/docs.pact.io/pull/128/files

you can pull it down and run it locally to see the changes.

`cd website && npm i && npm run start`

@PauloGoncalvesBH more diagrams are also good, I've raised a PR above , love your diagrams, have you got the raw input for web sequence diagram or an english version perhaps?

**Pull request merged**
