### PR TITLE
docs: include example of nirvana implementation

### PR DESCRIPTION
**Pull request by PauloGoncalvesBH**
Result at https://deploy-preview-168--docs-pact-io.netlify.app/pact_nirvana: 
image

### CODE REVIEW

**Comment by bethesque** [comment]
I love the codebase! Ideally we should have an official Pact or Pactflow diamond codebase however. The [example-consumer](https://github.com/pactflow/example-consumer) and [example-provider](https://github.com/pactflow/example-provider) should be diamond standard, shouldn't they?

**Comment by bethesque** [comment]
Tagging @YOU54F

**Comment by YOU54F** [comment]
Hey hey, this is indeed awesome, but as Beth points out, our canonical example-consumer and provider (and the interchangeable equivalents) should provide official maintained representations on the pact-nirvana setup.

I would love to promote the repository, along with the other great repositories out there for Pact in the wild. We don't really have a home for them in the docs, and surfacing them in a single place would be useful.

We have community blogs and videos - https://docs.pact.io/blogs_videos_and_articles

a page for community repos/implementations would be good, with a section for pact-nirvana implementations? 

I'd also like to take the time to update the pact-nirvana and the associated example repos to support

- publishing with branch property
- verifying with branch property
- recording deployments with record-deployment command
- using can-i-deploy to target environments, rather than tags
- using the latest webhook `contract_requiring_verification_published` link [here](https://docs.pact.io/pact_broker/webhooks#using-webhooks-with-the-contract_requiring_verification_published-event)

As the webhook is our recommend configuration at the moment, and has these pre-reqs

Use of this webhook requires that:

* the provider's [main branch](/pact_broker/branches#pacticipant-main-branch-property) is configured
* verification results are [published with the branch property](/pact_broker/branches#configuring-the-branch-when-publishing-verification-results) or you are [tagging with the branch name and have automatic branch creation turned on](/pact_broker/branches#automatic-branch-creation-from-first-tag) (even if you use trunk based development, and only ever use one branch)
* the exact commit of a provider version can be determined from the version number used to publish the verification results (ie. it either _is_ the commit, or _contains_ the commit as per the Pact Broker [version number guidelines](/getting_started/versioning_in_the_pact_broker#guidelines))
* any deployments and releases are recorded using the [`record-deployment` and `record-release` commands](/pact_broker/recording_deployments_and_releases).

A webhook using the `contract_requiring_verification_published` should be configured to pass through the `${pactbroker.pactUrl}` and `${pactbroker.providerVersionNumber}` and `${pactbroker.providerVersionBranch}` to the provider verification build. The build should ensure that the commit and branch that is specified by the `${pactbroker.providerVersionNumber}` and `${pactbroker.providerVersionBranch}` is checked out (as a commit can belong to more than one branch, some CI systems require that the branch is set as well as the commit - this helps to ensure that the verification results are published with the right branch too). If the provider version number _is_ the commit then this can generally be achieved by specifying the commit in the API call to the CI application that triggers the build.

**Comment by YOU54F** [comment]
Hey @rafael-anachoreta , 

I've created a new page on the website to host community repos and you are at the top of the list

https://docs.pact.io/community_repos#full-workflows

Thanks for this!

**Comment by rafael-anachoreta** [comment]
@YOU54F you probably meant to tag @PauloGoncalvesBH 🙂

**Comment by YOU54F** [comment]
> @YOU54F you probably meant to tag @PauloGoncalvesBH 🙂

Ahh sorry gentlemen 🤦🏾 ! Thanks @PauloGoncalvesBH for this, and thanks @rafael-anachoreta for kicking off the push to get the updates across the docs in the first place <3

**Comment by PauloGoncalvesBH** [comment]
@YOU54F WOOW, that's awesome, thank you

**Pull request closed without merging**
