### PR TITLE
docs: improve the formatting of Community Projects page

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Review by PauloGoncalvesBH — CHANGES_REQUESTED** [review]
I think that in this way, removing the username and GitHub project name will give less credit to community projects.
The `Description` step already explains the goal of the project.

When giving credit we need to be verbose to encourage more people to share their knowledge.

**Comment by sergeyklay** [comment]
I don't mind adding a field, such as "Author", but what I think is not quite accurate is that instead of human-readable project name, we use an URL that may not always reflect the subject, be unreadable, changed (due to renaming the project), etc.

**Comment by YOU54F** [comment]
Thanks team!

Would an Author link be useful? which could link to a users preferred contact/bio (GitHub profile, Twitter, Blog etc?)

If we were worried about things going out of date, we could always use a more intelligent way of getting the data, lots of options of that, but we could have a means for users tagging a repo with `pact-community-project`, and a script that could look for repos with those tags, and ingest that into structured data.


An example is https://tools.openapis.org/

https://github.com/OAI/Tooling#how-can-you-help

Their associated blog post is here

https://www.openapis.org/blog/2023/03/08/tools-that-support-openapi-specification

I like the idea of that, but there isn't really attribution to community members in there, similar to 

https://openapi.tools/#testing

I want to wholly promote the individuals making the content, more than the content itself, but maybe that might be better served by a community advocacy page, where community members can dedicate a page to themselves and all the things they are up to in the Pact & Contract testing community.

We've done a couple of community spotlights in the Pact open source blog posts recently such as, but having a dedicated place for people outside of the blog might be nice,

https://docs.pact.io/blog/2022/07/26/pact-open-source-update-july-2022#community-spotlight--mike-geeves

**Comment by sergeyklay** [comment]
Should I refine the current Pull Request in any way?

**Comment by YOU54F** [comment]
I'd be happy with these changes plus an Author field and link to the users github repo or profile.

Paulo would you want to see the repo link/name explicitly, the authors profile, or both

The other discussions we can talk about in the future :)

**Comment by PauloGoncalvesBH** [comment]
> I'd be happy with these changes plus an Author field and link to the users github repo or profile.
> 
> Paulo would you want to see the repo link/name explicitly, the authors profile, or both
> 
> The other discussions we can talk about in the future :)

I'd be happy with the same as you: An author field and a link to the GitHub repo or profile.

**Comment by sergeyklay** [comment]
@YOU54F Done. Could you please take a look? 

/cc @PauloGoncalvesBH

**Comment by YOU54F** [comment]
Thanks team <3

**Pull request merged**
