### PR TITLE
docs: Feature toggles initial draft

### PR DESCRIPTION
**Pull request by davidvc**
Here is an initial draft of a guide for using feature toggles.

I still have an open item for what to do around provider verification, with an open question on Slack about this.

But I thought it would be good to get feedback on the reset of it in the meantime

### CODE REVIEW

**Comment by YOU54F** [comment]
feature toggle page deploy

https://deploy-preview-133--docs-pact-io.netlify.app/getting_started/feature_toggles

**Comment by davidvc** [comment]
That page deploy is nice! I have more details on how to do provider verification when using environments, releases and deploys. I'm not sure you can solve this easily with pure tags; I need to look into this more.

**Comment by davidvc** [comment]
@bethesque @mefellows I looked at the new webhook, for the `content requiring verification published` event. It is sooo close but I think it won't work with feature flags. The reason is it verifies the __latest__ version on the main branch. If you have multiple active feature toggles on the main branch, you want to verify all of them.

I'm not sure how we would resolve this. Essentially one code version (the latest version on the branch) has multiple toggle versions. With the current data model, there is no direct way to know which toggle versions are part of the latest code version on the branch.  

But maybe for now it's sufficient to verify each version currently deployed to an environment? The risk is that you merge a toggle version into main that's not compatible with a consumer, and you wouldn't find out until you tried to deploy or release to environment and you realize that that version has not yet been verified.  So it won't cause failures in environments, but it will cause pipelines to block until you kick off the necessary verifications.

Hopefully I'm missing something?

**Comment by YOU54F** [comment]
Hey @mefellows , @bethesque , @uglyog 

Wondered if we could get a penny for your thoughts, came from a question by our recent doc wizard @davidvc 

> Hey, good evening. I wanted to let you know I'm kind of stuck with the feature flag work because I don't have good guidance on how someone will ensure that the right provider versions participate in verification.  The new webhook will run the verification job for all versions of the provider that are deployed or released, plus the latest version on the main branch.  But we actually need to test all versions on the main branch that are current (e.g. the base version,  plus all the toggle versions).

**Comment by YOU54F** [comment]
Hey hey, going to release this today and see how we get on with feedback.

Will try and build out an example when time permits

**Pull request merged**
