### PR TITLE
Communicate about new Pact contribution

### PR DESCRIPTION
**Pull request by opicaud**
Hello,

I have worked to associate Pact within Bazel by providing [rules_pact](https://github.com/opicaud/rules_pact)
The good news is that `rules_pact` has been accepted to be part of the official Bazel Central Registry https://registry.bazel.build/modules/rules_pact

Happy to share this contribution with you guys and again thanks to help teams to facilitate their testing journey :)
Voilà :)

Olivier

### CODE REVIEW

**Comment by YOU54F** [comment]
do you have links at all to the docs for criteria to satisfy for acceptance into the bazel central registry.

just more for curiosity, always interesting to see what differing package managers have and how they differ. some of it may shape our own guidelines perhaps

**Comment by opicaud** [comment]
Hey @YOU54F,

Shall I introduce myself at the session of this evening ?

[Here](https://github.com/bazelbuild/bazel-central-registry/pull/1101) is the PR, and the doc to add a new module is [here](https://github.com/bazel-contrib/publish-to-bcr/)

The process to add a module consists to add a `.bcr` folder with some metadata and a pipeline to be ran in the future PR. Activate the bcr app in your rules repo and in your fork of the bazel-central-registry repo. 

Then, each time a new release is available, a new PR is automagically opened in the official bazel-central-registry repo :)
Let's see in the future release if i will still need a manual approval or if it will be automatically added after the execution of the  pipeline.

**Comment by YOU54F** [comment]
up to you if you wish to attend and say hello! no pressure. i've posted a link to the PR in the group

**Comment by opicaud** [comment]
Hi all,

Any update on this PR? 
Thanks!

Olivier

**Comment by YOU54F** [comment]
sorry for the delay @opicaud

**Pull request merged**
