### PR TITLE
Chore/smartbear supported beta

### PR DESCRIPTION
**Pull request by mefellows**
A placeholder for a broader "smartbear supported" guide.

I've also added sidebars to the "help" section on the site, which was lacking for some reason.

### CODE REVIEW

**Comment by mefellows** [comment]
Let me know what you think: https://deploy-preview-232--docs-pact-io.netlify.app/help/smartbear

**Comment by YOU54F** [comment]
looks great, did you want to add in the imagine showing the  smartbear supported label to the help post?

**Review by YOU54F — APPROVED** [review]

**Comment by mefellows** [comment]
> looks great, did you want to add in the imagine showing the smartbear supported label to the help post?

Thanks. I originally added it in for another FAQ item, but I retracted that for now (it didn't look so helpful with the current content either). I did consider if I should check-in the image if not used - should I just pull it out for now?

**Comment by YOU54F** [comment]
OK with the image remaining if its not pulled it but no harm removing if its not used. Nice one for this PR 👍🏾

**Pull request merged**
