### PR TITLE
docs: "OpenAPI" without a blank, and "document" not "specification"

### PR DESCRIPTION
**Pull request by patricekrakow**
* "OpenAPI", when referring to the "OpenAPI Specification" (formerly Swagger), should be written without a blank between "Open" and "API". "Open API", with a blank, has a different meaning being and "API" which is "Open" ;-)

* The contract by the provider of a specific API is called an OpenAPI **document**. The term "OpenAPI Specification", OAS in short, is reserved for the _"standard, language-agnostic interface to HTTP APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection. [...] An OpenAPI document uses and conforms to the OpenAPI Specification."_ see <https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md>.

### CODE REVIEW

**Comment by patricekrakow** [comment]
Mmm, I have tried the prefixes "fix:" and "docs:" following information at https://github.com/zeke/semantic-pull-requests, but it did not fix the failing "Semantic Pull Request" check.

**Comment by mefellows** [comment]
It's not just the PR title that matters - it's the commit _message_ :)

Screen Shot 2022-02-04 at 9 04 18 am

**Comment by patricekrakow** [comment]
OK, thanks! Do you know what are the requirements? I did not find any indications about how the commit message should look like in the [CONTRIBUTING.md](https://github.com/pact-foundation/docs.pact.io/blob/master/CONTRIBUTING.md) file.

**Comment by mefellows** [comment]
Ah! So you're right, it looks like that got removed sometime. I've just fixed that up now, apologies for the confusion. 

The next contributor will indeed benefit from this though, so you can consider this two contributions :)

**Comment by mefellows** [comment]
For clarity, your PR title will suffice as the commit message.

**Comment by patricekrakow** [comment]
Wow, you have pushed my knowlege of git, I have done my very first `git rebase` following the instructions from <https://linuxize.com/post/change-git-commit-message/>. I hope it will be OK; at least the "Semantic Pull Request" check is now passed :-)

**Comment by patricekrakow** [comment]
Mmm, I am now wondering why this PR is showing 3 files changed while I have only changed one file `website/docs/getting_started.md`, let me know if I messed up something... Maybe I should close this PR, delete my fork and restart from scratch... What do you think?

**Comment by mefellows** [comment]
> Maybe I should close this PR, delete my fork and restart from scratch... What do you think?

Yes, probably not a bad idea! There are other ways, but for such a small change that's what I'd do. 

Sorry, but I want you to get the commit contribution for your efforts!

**Comment by patricekrakow** [comment]
No problem, I will redo my change so we don't mess up the Git history.

**Pull request closed without merging**
